
export const RESET_ALL_EXAM = 'RESET_ALL_EXAM';
export const FETCH_EXAM_SUCCESS = 'FETCH_EXAM_SUCCESS';
export const FETCH_ALL_EXAMS_SUCCESS = 'FETCH_ALL_EXAMS';
export const FETCH_EXAM_FAIL = 'FETCH_EXAM_FAIL';

export const CLOSE_EXAM_SUCCESS = 'CLOSE_EXAM_SUCCESS';
export const CLOSE_EXAM_FAIL = 'CLOSE_EXAM_FAIL';

export const TOGGLE_STUDENT_SUCCESS = 'TOGGLE_STUDENT_SUCCESS';
export const TOGGLE_STUDENT_FAIL = 'TOGGLE_STUDENT_FAIL';