export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_WAITING = 'NOTIFICATION_WAITING';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';