export const FETCH_SUPERVISOR = 'FETCH_SUPERVISOR';
export const FETCH_SUPERVISOR_SUCCESS = 'FETCH_SUPERVISOR_SUCCESS';
export const FETCH_SUPERVISOR_FAIL = 'FETCH_SUPERVISOR_FAIL';
export const SUPERVISOR_DICONNECT = 'SUPERVISOR_DICONNECT';
